//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBase_Barcodes.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>[Meadows]Data Source=10.209.41.166:1521/MEADOW;User ID=viewer;Password=cprt_hsi;Unicode=True</string>
  <string>[Triumph]Data Source=10.209.41.166:1521/TRIUMP;User ID=viewer;Password=cprt_hsi;Unicode=True</string>
  <string>[UMass]Data Source=10.209.41.166:1521/UMASS;User ID=viewer;Password=cprt_hsi;Unicode=True</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ConnectionStrings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ConnectionStrings"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp")]
        public string TempDirectory {
            get {
                return ((string)(this["TempDirectory"]));
            }
        }
    }
}
